Added info from folder files to ArrayList
typeundefined/edu-fileexplorer-2019 pull request #1
Opened 2019-10-22 20:50 UTC by ilya-as

1.В файл application.properties добавлена настройка pathToPublish с абсолютным путем к папке
2.Для чтения настроек реализован класс Config
3.Добавлен тест ConfigTest для проверки чтения настройки pathToPublish 
4.Для хранения атрибутов файлов создан класс FileStore.
5.Так как нам требуется хранить сериализованный список файлов,у класса FileStore добавлена имплементация интерфейса Serializable и для хранения списка была выбрана поддерживающая сериализацию коллекция ArrayList.
5.Создание списка файлов List<FileStore> из переданной папки реализовано в классе FileExplorerService.Класс имплементирует интерфейс FileExplorer.
6. Для проверки получения списка файлов из переданной папки добавлен тест FileExplorerTest

2019-10-23 06:00 UTC, typeundefined requested changes

2019-10-23 06:00 UTC, typeundefined commented on src/main/java/ru/amm/fileexplorer/server/utils/Config.java
> +public class Config {
Вы переизобретаете велосипед. Spring такие вещи делает за вас. Поищите информацию про аннотацию `@Value`

2019-10-23 06:00 UTC, typeundefined commented on src/main/java/ru/amm/fileexplorer/server/FileExplorer.java
> +    public List<FileStore> getFileList(String path) throws IOException;
А нужен ли нам Checked exception в интерфейсе?

2019-10-23 18:14 UTC, ilya-as commented on src/main/java/ru/amm/fileexplorer/server/FileExplorer.java
> +    public List<FileStore> getFileList(String path) throws IOException;
Исправил

2019-10-23 18:14 UTC, ilya-as commented on src/main/java/ru/amm/fileexplorer/server/utils/Config.java
> +public class Config {
Переделал на аннотации.

2019-10-24 13:04 UTC, typeundefined approved these changes

2019-10-24 14:37 UTC, merged