Issues #10 resolved
typeundefined/edu-fileexplorer-2019 pull request #17
Opened 2019-10-31 18:47 UTC by Saoqq

Велосипед с %root% нужен для отключения отображения перехода в родительский каталог для случая, когда пользователь находится в каталоге pathToPublish.
(Читается не очень, автоформатирование git тоже подятнул)

2019-10-31 18:48 UTC, Saoqq commented on src/main/resources/templates/index.ftl
>  </#macro>
По факту только это изменение

2019-11-01 17:43 UTC, Saoqq commented on src/main/java/ru/amm/fileexplorer/server/entity/NamePartialMatcher.java
> +}
Matcher для частичного совпадения имени

2019-11-01 17:43 UTC, Saoqq commented on src/main/java/ru/amm/fileexplorer/server/service/FileExplorerService.java
> +
Поиск фильтрация по всем подкаталогам

2019-11-01 17:55 UTC, Saoqq commented on src/main/resources/static/scripts/sc.js
> +}
Вызов ajax.
Нерационально используются ресурсы сервера, при введении нового символа идет новый запрос,
соответственно старый запрос клиентом откланяется. 
Если для поиска по текущей директории еще применимо, то для поиска по поддиректориям выглядит очень плохо.
Как вариант для поиска по поддиректориям сделать активацию по кнопке.
Далее прозвучит глупая мысль.
Второй вариант:
обрабатывать новый запрос и прерывать старый, а для прерывания нужно хранить этот поток и т.д. и т.п.
Насколько второй вариант жизнеспособен и применяется ли такое на практике?

2019-11-01 17:55 UTC, Saoqq commented on src/main/resources/templates/filesView.ftl
> +</#list>
Вынесен макрос для отображения файлов в отдельный шаблон

2019-11-01 17:56 UTC, Saoqq commented on src/main/resources/templates/index.ftl
> +        <@macro.show_all directory/>
Тянем макрос и вызываем метод с параметром directory

2019-11-01 17:57 UTC, Saoqq commented on src/main/java/ru/amm/fileexplorer/server/IndexController.java
> +    }
Поиск по текущей директории и по поддиректориям соответственно

2019-11-03 21:57 UTC, Saoqq commented on src/main/java/ru/amm/fileexplorer/server/service/FileSystemProvider.java
> +        }
Может кинуть null, нужно будет выбрать какое-то значение по умолчанию.

2019-11-03 22:00 UTC, Saoqq commented on src/main/java/ru/amm/fileexplorer/server/IndexController.java
> +    }
В UI добавил кнопочку скачивания, можно скачивать как файлы, так и директории полностью. 
Для директорий сначала все загоняется во временный .zip, а уже потом отдается клиенту.

2019-11-05 15:49 UTC, typeundefined commented on src/main/resources/static/scripts/sc.js
> +}
Насчет второго варианта с отменой длительного запроса на сервере - это имхо сделать не так просто, учитывая что у нас нет даже блокирующих вызовов.

Я бы ограничился только тем, чтобы завести ограниченный пул тредов, которые в принципе могут работать с файловой системой. Просто, чтобы не убить контроллер диска тысячей однотипных сканов.

2019-11-05 15:50 UTC, typeundefined commented on src/main/java/ru/amm/fileexplorer/server/entity/NamePartialMatcher.java
> +}
А чем он принципиально отличается от `NameMatcher`?

2019-11-05 15:52 UTC, typeundefined commented on src/main/java/ru/amm/fileexplorer/server/IndexController.java
> +    }
Вообще поиск по поддиректориям я не требовал (потому, что выборка будет потенциально *слишком* большой). Для этого уже стоит заводить и отдельный UX с пейджинацией и расширять отображение (раз выводятся файлы из разных каталогов, то надо показывать как-то и эти самые каталоги и давать возможность перейти в этот каталог и тп).

2019-11-05 15:53 UTC, typeundefined commented on src/main/java/ru/amm/fileexplorer/server/service/FileSystemProvider.java
> +        }
В любом случае проглатывать exception - это очень плохая практика. Так не надо делать.

2019-11-05 16:05 UTC, Saoqq commented on src/main/java/ru/amm/fileexplorer/server/entity/NamePartialMatcher.java
> +}
Не совсем понял вопроса. Основное отличие - частичное совпадение имени, а не полное.

2019-11-05 16:07 UTC, Saoqq commented on src/main/java/ru/amm/fileexplorer/server/IndexController.java
> +    }
Да, я прекрасно понимал, что искать по поддиректориям плохая затея, сделал потому что хотелось )

2019-11-06 09:32 UTC, typeundefined commented on src/main/java/ru/amm/fileexplorer/server/entity/NamePartialMatcher.java
> +}
Прошу прощения, проглядел.

2019-11-06 10:14 UTC, typeundefined commented on src/main/java/ru/amm/fileexplorer/server/IndexController.java
> +        if (f.isDirectory()) {
Вообще фича "скачать директорию" не входила в требования :-) Но ок, спасибо

2019-11-06 10:14 UTC, typeundefined commented on src/main/java/ru/amm/fileexplorer/server/IndexController.java
> +            type = f.getMimeType().split("/");
Здесь я получаю NPE для некоторых файлов. Это баг.

2019-11-06 10:18 UTC, typeundefined commented on src/main/java/ru/amm/fileexplorer/server/service/FileSystemProvider.java
> +        return path.orElse("%root%");
Мне не нравится это решение. К слову, на Linux `%root%` вполне себе валидное имя для файла или директории.

2019-11-06 10:25 UTC, typeundefined commented on src/main/java/ru/amm/fileexplorer/server/service/FileSystemProvider.java
> +            Path f = Path.of(pathToPublish + "\\" + relativePath);
Не на всех ОС разделителем является обратный слэш (`\`). Как вариант можно воспользоваться [`Paths.get()`](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Paths.html#get-java.lang.String-java.lang.String...-)

2019-11-06 10:26 UTC, typeundefined commented on src/main/java/ru/amm/fileexplorer/server/service/FileSystemProvider.java
> +            zos.close();
В случае exception `zos` окажется не закрыт. Это утечка ресурсов.

2019-11-06 10:26 UTC, typeundefined commented on src/main/java/ru/amm/fileexplorer/server/service/FileSystemProvider.java
> +            Path f = Paths.get(pathToPublish + "/" + relativePath);
Конкатенацию можно просто заменить перечислением через запятую. И про разделитель уже думать не надо.

2019-11-06 10:46 UTC, typeundefined commented
closes #10, closes #9, closes #8

2019-11-06 10:47 UTC, typeundefined requested changes
Есть пара проблем (см. комментарии), но в целом работа очень хорошая.

2019-11-06 18:32 UTC, Saoqq commented on src/main/java/ru/amm/fileexplorer/server/service/FileSystemProvider.java
> +            }
Обернул в try /w resources

2019-11-06 18:35 UTC, Saoqq commented on src/main/resources/templates/filesView.ftl
> +        <#assign picture_source =file_type.base+'.svg'>
Выбор только по базовому типу файла.

2019-11-06 18:38 UTC, Saoqq commented
Не знаю как поступить с иконками, возможно имеет смысл в FileType притянуть проверку на существование иконки для данного типа, т.е. ищем иконку для расширения - не нашли, значит ставим базовый тип.

2019-11-10 10:47 UTC, typeundefined approved these changes
Есть шероховатости, но их мы можем поправить позже. Мержу.

2019-11-10 10:48 UTC, merged

2019-11-17 17:31 UTC, typeundefined commented on src/main/java/ru/amm/fileexplorer/server/service/FileSystemProvider.java
> +                zos.close();
Если zos стоит под `try (..)` то закрывать его уже не надо