Implemented create directory Issue#21
typeundefined/edu-fileexplorer-2019 pull request #25
Opened 2019-11-18 20:45 UTC by skylinedb

@typeundefined #21 
Решил вопросы с редиректом.
Также добавил название новой папки по умолчанию если вдруг её никак не назовут.
Ко всему этому прикрутил csrf

2019-11-21 08:26 UTC, typeundefined requested changes

2019-11-21 08:26 UTC, typeundefined commented on src/main/java/ru/amm/fileexplorer/server/controller/IndexController.java
> +        File dir = new File(absPath);
Бизнес-логика не должна быть в контроллере.

2019-11-21 08:26 UTC, typeundefined commented on src/main/java/ru/amm/fileexplorer/server/controller/IndexController.java
> +        String absPath = pathToPublish + "\\" + path + "\\" + newNameOfFolder;
Путь - это не строка. Для пути есть отличное представление в виде `Path`. 

И конкатенация строк - это не есть хорошо. На линуксе или на маке такой код работать просто не будет.

2019-11-21 08:26 UTC, typeundefined commented on src/main/resources/templates/index.ftl
> +            <form name="createDirForm" action="/createDir" enctype="multipart/form-data"
А зачем нам тут multipart?

2019-11-21 08:36 UTC, typeundefined commented on src/main/java/ru/amm/fileexplorer/server/controller/IndexController.java
> +            nameOfFolder = baseNameOfFolder;
Зачем? Если нам не пришло корректное имя, то запрос просто некорректен

2019-11-21 08:40 UTC, typeundefined requested changes

2019-11-21 08:40 UTC, typeundefined commented on src/main/java/ru/amm/fileexplorer/server/controller/IndexController.java
> +            newNameOfFolder = baseNameOfFolder;
Зачем вообще нужен baseNameOfFolder? Что пользователь попросил, то мы и создаем, не больше и не меньше

2019-11-21 08:40 UTC, typeundefined commented on src/main/java/ru/amm/fileexplorer/server/controller/IndexController.java
> +            newNameOfFolder = nameOfFolder.replaceAll(baseNameOfFolder + ",", "");
Тем более, что оказывается создать папочку с именем "NewFolder," я как пользователь не смогу. Почему?

2019-11-21 08:40 UTC, typeundefined commented on src/main/java/ru/amm/fileexplorer/server/controller/IndexController.java
> +        dir.mkdir();
В документации говорится, что результат этого метода нужно проверять. Он не бросит exception, если папку создать не удалось

2019-11-21 10:59 UTC, skylinedb commented on src/main/java/ru/amm/fileexplorer/server/controller/IndexController.java
> +            newNameOfFolder = baseNameOfFolder;
Сделано по примеру обычного файлового менеджера на компьютере, если не давать название то создается новая папка, имя которой определено в application.properties. Подумал что такая логика будет правильнее))

2019-11-21 10:59 UTC, skylinedb commented on src/main/java/ru/amm/fileexplorer/server/controller/IndexController.java
> +            newNameOfFolder = nameOfFolder.replaceAll(baseNameOfFolder + ",", "");
Попробовал создать сейчас папку под названием NewFolder, все работает

2019-11-21 12:10 UTC, skylinedb commented
@typeundefined 
Подкорректировал реализацию, убрал бизнес логику внутрь, сделал по образу и подобию загрузки файлов

2019-11-28 12:30 UTC, skylinedb commented
@typeundefined 
Мне обновить ветку до orgin и заново добавить реализацию?

2022-04-13 18:27 UTC, closed without merging