Implemented Issue#12
typeundefined/edu-fileexplorer-2019 pull request #27
Opened 2019-11-19 20:43 UTC by AntonS2000

Добавлена кастомная аннотация RelativePath, с помощью которой можно проверять относительные пути в запросах на корректность.

2019-11-21 08:22 UTC, typeundefined requested changes

2019-11-21 08:22 UTC, typeundefined commented on src/main/java/ru/amm/fileexplorer/server/validator/RelativePathValidator.java
> +        absolutePath = FilenameUtils.normalize(absolutePath);
С этим вроде бы справится и обычный `Path` из Java 8. На мой взгляд, нет смысла тянуть лишнюю зависимость и играться с конкатенацией строк

2019-11-21 08:22 UTC, typeundefined commented on src/main/java/ru/amm/fileexplorer/server/validator/RelativePathValidator.java
> +public class RelativePathValidator implements ConstraintValidator<RelativePath, String> {
А если воспользоваться [интерфейсом Validator](https://docs.spring.io/spring/docs/4.1.x/spring-framework-reference/html/validation.html#validator) из Spring, то никакие фабрики конструировать уже не пришлось бы ;-)

2019-11-21 08:36 UTC, AntonS2000 commented on src/main/java/ru/amm/fileexplorer/server/validator/RelativePathValidator.java
> +        absolutePath = FilenameUtils.normalize(absolutePath);
По идее нужно сделать несколько валидаторов для разных типов данных?

2019-11-21 08:49 UTC, AntonS2000 commented on src/main/java/ru/amm/fileexplorer/server/validator/RelativePathValidator.java
> +public class RelativePathValidator implements ConstraintValidator<RelativePath, String> {
Я хотел использовать аннотации для валидации, получится сделать это вашим способом?

2019-11-21 08:49 UTC, AntonS2000 commented on src/main/java/ru/amm/fileexplorer/server/validator/RelativePathValidator.java
> +public class RelativePathValidator implements ConstraintValidator<RelativePath, String> {
Я хотел использовать аннотации для валидации, получится сделать это вашим способом?

2019-11-21 13:07 UTC, AntonS2000 commented on src/main/java/ru/amm/fileexplorer/server/validator/RelativePathValidator.java
> +        absolutePath = FilenameUtils.normalize(absolutePath);
заменил FilenameUtils.normalize() на Path.normalize()

2019-11-27 13:32 UTC, typeundefined commented on src/main/java/ru/amm/fileexplorer/server/validator/RelativePathValidator.java
> +public class RelativePathValidator implements ConstraintValidator<RelativePath, String> {
Разумеется :-)

2019-11-28 10:11 UTC, merged